# Template
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: wordpress
labels:
  template: wordpress

parameters:
  - name: "NAMESPACE"
    required: false
  - name: "ENVIRONMENT"
    required: true
  - name: "APP_NAME"
    required: true
  - name: "DB_NAME"
    required: true
  - name: "WORDPRESS_CURRENT_SITE"
    required: true
  - name: "RESOURCES_REQUEST_CPU"
    required: true
  - name: "RESOURCES_REQUEST_MEMORY"
    required: true
  - name: "RESOURCES_LIMIT_CPU"
    required: true
  - name: "RESOURCES_LIMIT_MEMORY"
    required: true

objects:
  
  # BuildConfig 
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app.kubernetes.io/name: "${APP_NAME}-build"
        app.kubernetes.io/part-of: "${APP_NAME}"
        app.kubernetes.io/component: "wordpress"
        app.kubernetes.io/version: "2.0"
        app.kubernetes.io/managed-by: "kustomize"
        app: "${APP_NAME}"
      name: ${APP_NAME}
    spec:
      failedBuildsHistoryLimit: 1
      successfulBuildsHistoryLimit: 1
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}:${ENVIRONMENT}
      postCommit: {}
      resources:
        limits:
          memory: "2Gi"
      runPolicy: Serial
      source:
        binary:
          contextDir: .
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile

  # ImageStream
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        app.kubernetes.io/name: "${APP_NAME}-image"
        app.kubernetes.io/part-of: "${APP_NAME}"
        app.kubernetes.io/component: "wordpress"
        app.kubernetes.io/version: "2.0"
        app.kubernetes.io/managed-by: "kustomize"
        app: "${APP_NAME}"
      name: ${APP_NAME}
    spec:
      lookupPolicy:
        local: true

  # Persistent Volume Claim
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: wordpress-content
      labels:
        app.kubernetes.io/name: "${APP_NAME}-content"
        app.kubernetes.io/part-of: "${APP_NAME}"
        app.kubernetes.io/component: "wordpress"
        app.kubernetes.io/version: "2.0"
        app.kubernetes.io/managed-by: "kustomize"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  
  # Deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${APP_NAME}
      labels:
        app.kubernetes.io/name: "${APP_NAME}-deploy"
        app.kubernetes.io/part-of: "${APP_NAME}"
        app.kubernetes.io/component: "wordpress"
        app.kubernetes.io/version: "2.0"
        app.kubernetes.io/managed-by: "kustomize"
      annotations:
        image.openshift.io/triggers: >-
          [{ "from": {
                "kind": "ImageStreamTag",
                "name": "${APP_NAME}:${ENVIRONMENT}"
             },
             "fieldPath": "spec.template.spec.containers[?(@.name==\"wordpress\")].image",
             "pause": false
          }]
    spec:
      replicas: 1
      revisionHistoryLimit: 1
      selector:
        matchLabels:
          app: ${APP_NAME}
          component: wordpress
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            component: wordpress
            technology: mysql
            backup: daily
        spec:
          containers:
            - name: wordpress
              image: "${APP_NAME}:${ENVIRONMENT}"
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: ${RESOURCES_REQUEST_CPU}
                  memory: ${RESOURCES_REQUEST_MEMORY}
                limits:
                  cpu: ${RESOURCES_LIMIT_CPU}
                  memory: ${RESOURCES_LIMIT_MEMORY}
              ports:
                - containerPort: 8080
                  name: http
              volumeMounts:
                - name: wordpress-content
                  mountPath: /var/www/html/wp-content
              readinessProbe:
                exec:
                  command:
                    - curl
                    - -H
                    - "X-K8S-PROBE: dummy"
                    - http://127.0.0.1:8080/health.php
                initialDelaySeconds: 3
                timeoutSeconds: 3
              livenessProbe:
                exec:
                  command:
                    - curl
                    - -H
                    - "X-K8S-PROBE: dummy"
                    - http://127.0.0.1:8080/health.php
                initialDelaySeconds: 360
                timeoutSeconds: 10
              envFrom:
                - secretRef:
                    name: ${DB_NAME}-login
                  prefix: WORDPRESS_DB_
                - secretRef:
                    name: ${DB_NAME}-login
                  prefix: MYSQL_
              env:
                - name: ENVIRONMENT
                  value: ${ENVIRONMENT}
                - name: K8S_PROBE
                  value: dummy
                - name: WORDPRESS_TABLE_PREFIX
                  value: wp_
                - name: WORDPRESS_CURRENT_SITE
                  value: ${WORDPRESS_CURRENT_SITE}
          volumes:
            - name: wordpress-content
              persistentVolumeClaim:
                claimName: wordpress-content
  
  # Service
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/name: "${APP_NAME}-svc"
        app.kubernetes.io/part-of: "${APP_NAME}"
        app.kubernetes.io/component: "wordpress"
        app.kubernetes.io/version: "2.0"
        app.kubernetes.io/managed-by: "kustomize"
        app: "${APP_NAME}"
        component: "wordpress"
      name: "${APP_NAME}"
    spec:
      ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      - name: 8443-tcp
        port: 8443
        protocol: TCP
        targetPort: 8443
      selector:
        app: ${APP_NAME}
        component: wordpress
      sessionAffinity: None
      type: ClusterIP
  
  # Route
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt
        cert-manager.io/renew-before: 24h
        haproxy.router.openshift.io/hsts_header: max-age=31536000
      labels:
        app.kubernetes.io/name: "${APP_NAME}-route"
        app.kubernetes.io/part-of: "${APP_NAME}"
        app.kubernetes.io/component: "wordpress"
        app.kubernetes.io/version: "2.0"
        app.kubernetes.io/managed-by: "kustomize"
        app: "${APP_NAME}"
      name: ${APP_NAME}
    spec:
      host: www.${WORDPRESS_CURRENT_SITE}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${APP_NAME}
        weight: 100
      wildcardPolicy: None
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt
        cert-manager.io/renew-before: 24h
        haproxy.router.openshift.io/rewrite-target: "https://www.${WORDPRESS_CURRENT_SITE}$1"
        haproxy.router.openshift.io/hsts_header: "max-age=31536000"
      labels:
        app.kubernetes.io/name: "${APP_NAME}-route"
        app.kubernetes.io/part-of: "${APP_NAME}"
        app.kubernetes.io/component: "wordpress"
        app.kubernetes.io/version: "2.0"
        app.kubernetes.io/managed-by: "kustomize"
        app: "${APP_NAME}"
      name: naked
    spec:
      host: ${WORDPRESS_CURRENT_SITE}
      port:
        targetPort: http
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: wordpress-svc
        weight: 100
      wildcardPolicy: None
